const dec=[
    {
        date:"03/12/2025",
        expenses:[
            {
                name:"rice",
                amount:"190",
                quantity:"2kg"
            },{
                name:"tomatoes",
                amount:"100",
                quantity:"1kg"
            },{
                name:"drink",
                amount:"20",
                quantity:"500ml"
            }
        ]
    },{
        date:"04/12/2025",
        expenses:[
            {
                name:"bread",
                amount:"45",
                quantity:"1 loaf"
            },
            {
                name:"drink",
                amount:"20",
                quantity:"500ml"
            },
            {
                name:"eggs",
                amount:"35",
                quantity:"5-pieces"
            }
        ]
    },
    {
        date:"05/12/2025",
        expenses:[
            {
                name:"coffee",
                amount:"40",
                quantity:""
            },
            
        ]
    },
    {
        date:"09/12/2025",
        expenses:[
            {
                name:"drink",
                amount:"20",
                quantity:"500ml"
            },{
                name:"bread",
                amount:"40",
                quantity:"1 loaf"
            },
            {
                name:"lays",
                amount:"20",
                quantity:"1 packet"
            }
        ]
    },
    {
        date:"10/12/2025",
        expenses:[
            {
                name:"rice",
                amount:"90",
                quantity: "2kg"
            },
            {
                name:"drink",
                amount:"20",
                quantity:"50ml"
            },
            {
                name:"lays",
                amount:"20",
                quantity:"1 packet"
            }
        ]
    }
]