const firstSemResults={
    release_date:"11/03/2024",
    examination:"Nov  2023",
    results:[
        {
            s_no:1,
            rollNumber:"2305289",
            studentName:"Aarush Pupneja",
            FatherName:"Azad Pupneja",
            resultStatus:"re_appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
    
        {
            s_no:2,
            rollNumber:"2305290",
            studentName:"Abdul Ahad",
            FatherName:"Mohammad Khalid",
            resultStatus:"re_appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:3,
            rollNumber:"2305291",
            studentName:"Abhishek Kumar",
            FatherName:"Ashok Kumar Sinha",
            resultStatus:"re_appear",
            passed:false,
            credits:10,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:4,
            rollNumber:"2305294",
            studentName:"Anshu Sharma",
            FatherName:"Bhagwan Dass Sharma",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:8.00,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:5,
            rollNumber:"2305295",
            studentName:"Ashish Kallu",
            FatherName:"Gulu Ram",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.82,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:6,
            rollNumber:"2305296",
            studentName:"Ashvani Yadav",
            FatherName:"Narendra Yadav",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:6.76,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:7,
            rollNumber:"2305297",
            studentName:"Ayush Kumar",
            FatherName:"Haresh Kumar",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:6.71,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:8,
            rollNumber:"2305298",
            studentName:"Bappa Suklabadya",
            FatherName:"Bablu Suklabadya",
            resultStatus:"re-appear",
            passed:false,
            credits:2,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:9,
            rollNumber:"2305299",
            studentName:"Birenda Kumar",
            FatherName:"Madhu Prasad",
            resultStatus:"re-appear",
            passed:false,
            credits:2,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:10,
            rollNumber:"2305300",
            studentName:"Bishal Kumar Sah",
            FatherName:"Maheshwar Sah",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.94,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:11,
            rollNumber:"2305301",
            studentName:"Bizumuremyi Gervais",
            FatherName:"Patrick Mugenga",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:6.76,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:12,
            rollNumber:"2305302",
            studentName:"Desire Musarafu",
            FatherName:"Sheperd Musarafu",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:6.71,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:13,
            rollNumber:"2305303",
            studentName:"Faisal Ashraf Dar",
            FatherName:"Mohammad Ashraf Dar",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:14,
            rollNumber:"2305304",
            studentName:"Hanzala Safi",
            FatherName:"Safi Alam",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:15,
            rollNumber:"2305305",
            studentName:"Harmandeep Singh",
            FatherName:"Armajit Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:16,
            rollNumber:"2305306",
            studentName:"Husanpreet Singh",
            FatherName:"Jaswinder Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:17,
            rollNumber:"2305307",
            studentName:"Indrajeet Kumar Mukhiya",
            FatherName:"Vinod Mukhiya",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:6.71,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:18,
            rollNumber:"2305308",
            studentName:"Isha Thappa",
            FatherName:"Bharat Bushan",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:19,
            rollNumber:"2305309",
            studentName:"Jasleen Kaur",
            FatherName:"Harbans Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:20,
            rollNumber:"2305310",
            studentName:"Jaspreet Kaur",
            FatherName:"Amarjeet Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:21,
            rollNumber:"2305311",
            studentName:"Justin Wellington Chada",
            FatherName:"Max Chada",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:8.24,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:22,
            rollNumber:"2305312",
            studentName:"Karan Kumar Paswan",
            FatherName:"Dina Nath Paswan",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:23,
            rollNumber:"2305313",
            studentName:"Kashish",
            FatherName:"Varinder Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:10,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:24,
            rollNumber:"2305314",
            studentName:"Komalpreet Kaur",
            FatherName:"Kulbir Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:13,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:25,
            rollNumber:"2305315",
            studentName:"Lakshay Katoch",
            FatherName:"SehDev Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:26,
            rollNumber:"2305316",
            studentName:"Leishangthem Lojingngamba Khabha",
            FatherName:"Leishngathem Bobi Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass",
                },
               
            }
        },
        {
            s_no:27,
            rollNumber:"2305317",
            studentName:"MD Farhan Alam",
            FatherName:"Aftab Ahmad",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
            }
        },
        {
            s_no:28,
            rollNumber:"2305319",
            studentName:"MD Sahid Alam",
            FatherName:"Shabnam Pravin",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
            }
        },
        {
            s_no:29,
            rollNumber:"2305320",
            studentName:"Mohammad Anwar",
            FatherName:"MD MustaqueAhmad",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
            }
        },
        {
            s_no:30,
            rollNumber:"2305321",
            studentName:"Mohammad Umar Farooq",
            FatherName:"Mohammad Maqsood Alam",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:8.12,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:31,
            rollNumber:"2305322",
            studentName:"Muskan Kumari",
            FatherName:"Aklesh Parsad",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.88,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:32,
            rollNumber:"2305323",
            studentName:"Mwaalu Muloongo",
            FatherName:"Best Munyama Muloongo",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.24,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:33,
            rollNumber:"2305324",
            studentName:"Nikhil Kumar Singh",
            FatherName:"Jayprakash Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:34,
            rollNumber:"2305325",
            studentName:"Prakriti Upadhyay",
            FatherName:"Abhimanyu Upadhyay",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.76,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:35,
            rollNumber:"2305326",
            studentName:"Pritam Sinha",
            FatherName:"Golap Sinha",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:8.18,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:36,
            rollNumber:"2305327",
            studentName:"Rakesh Kumar",
            FatherName:"Ram Hriday Singh",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:6.47,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:37,
            rollNumber:"2305328",
            studentName:"Ravneet Kaur",
            FatherName:"Gurpreet Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:10,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:38,
            rollNumber:"2305329",
            studentName:"S Rehan Haider",
            FatherName:"Md Hasan",
            resultStatus:"re-appear",
            passed:false,
            credits:10,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass",
                },
            }
        },
        {
            s_no:39,
            rollNumber:"2305331",
            studentName:"Sajjad Ali",
            FatherName:"Syed Reyaz Al Rizvi",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:8.24,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
            }
        },
        {
            s_no:40,
            rollNumber:"2305332",
            studentName:"saurabh ",
            FatherName:"Sanveej Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:13,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
            }
        },
        {
            s_no:41,
            rollNumber:"2305333",
            studentName:"Shekina Nokukhanya Ncube ",
            FatherName:"Mkhanyiseli Ncube",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
            }
        },
        {
            s_no:42,
            rollNumber:"2305334",
            studentName:"Simranjeet Kaur",
            FatherName:"Rajinder Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass",
                },
            }
        },
        {
            s_no:43,
            rollNumber:"2305335",
            studentName:"Subhi Suman",
            FatherName:"Saroj Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:44,
            rollNumber:"2305336",
            studentName:"Thomas Isheansu Kazonda",
            FatherName:"Thomas Kazonda",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.59,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:45,
            rollNumber:"2305337",
            studentName:"Vanshika ",
            FatherName:"Sanjeev Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:13,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:46,
            rollNumber:"2305338",
            studentName:"Vanshika ",
            FatherName:"Charanjit Kumar",
            resultStatus:"pass",
            passed:true,
            credits:17,
            SGPA:7.12,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:47,
            rollNumber:"2305339",
            studentName:"Varinder Singh ",
            FatherName:"Satnam Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        },
        {
            s_no:48,
            rollNumber:"2305340",
            studentName:"Vipan Sharma",
            FatherName:"Ranjeep Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:14,
            SGPA:null,
            gradeDetails:{
                Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Basic_Electrical_Engineering:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass",
                },
                Basic_Electrical_Engineering_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass",
                },
                Engineering_Graphics_And_Design:{
                    qualitative_meaning:3,
                    gradeSymbol:"failed(external)",
                    status:"re-appear",
                },
                Engineering_Physics:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                Engineering_Physics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass",
                },
            }
        }
        
    ]
}



// console.log(firstSemResults.results)
export default firstSemResults