const secondSemResults = {
    release_date:"2/8/2024",
    results:[
        {
            s_no:1,
            rollNumber:2305289,
            studentName:"Aarush Pupneja",
            FatherName:"Azad Pupneja",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },

            }
        },
        {
            s_no:2,
            rollNumber:2305290,
            studentName:"Abdul Ahad",
            FatherName:"Mohammad Khalid",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },

            }
        },
        {
            s_no:3,
            rollNumber:2305291,
           studentName:"Abhishek Kumar",
            FatherName:"Ashok Kumar Sinha",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },

            }
        },
        {
            s_no:4,
            rollNumber:2305292,
           studentName:"Abhishek Thakur",
            FatherName:"Raj Kumar ",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.50,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },

            }
        },
        {
            s_no:5,
            rollNumber:2305293,
           studentName:"Amanjot Kaur",
            FatherName:"Lakhvir Singh",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.50,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },

            }
        },
        {
            s_no:6,
            rollNumber:2305294,
           studentName:"Anshu Sharma",
            FatherName:"Bhagwan Dass Sharma",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.50,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },

            }
        },
        {
            s_no:7,
            rollNumber:2305295,
           studentName:"Ashish Kallu",
            FatherName:"Gulu Ram",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.40,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:8,
            rollNumber:2305296,
           studentName:"Ashvani Yadav",
            FatherName:"Narendra Yadav",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.40,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:9,
            rollNumber:2305297,
           studentName:"Ayush Kumar",
            FatherName:"Haresh Kumar",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.00,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:10,
            rollNumber:2305298,
           studentName:"Bappa Suklabaidya",
            FatherName:"Bablu Suklabaidya",
            resultStatus:"re-appear",
            passed:false,
            credits:11,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:11,
            rollNumber:2305299,
           studentName:"Birenda Kumar",
            FatherName:"Madhu Prasad",
            resultStatus:"re-appear",
            passed:false,
            credits:12,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },

            }
        },
        {
            s_no:12,
            rollNumber:2305300,
           studentName:"Bishal Kumar Sah",
            FatherName:"Maheshwar Sah",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.25,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },

            }
        },
        {
            s_no:13,
            rollNumber:2305301,
           studentName:"Bizumremyi Gervais",
            FatherName:"Patrick Mugenga",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.65,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },

            }
        },
        {
            s_no:14,
            rollNumber:2305302,
           studentName:"Desire Musarafu",
            FatherName:"Sheppard Musarafu",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.90,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },

            }
        },
        {
            s_no:15,
            rollNumber:2305303,
           studentName:"Faisal Ashraf Dar",
            FatherName:"Mohammad Ashraf Dar",
            resultStatus:"re-appear",
            passed:false,
            credits:12,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"C+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:16,
            rollNumber:2305304,
           studentName:"Hanzala Safi",
            FatherName:"Safi Alam",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:17,
            rollNumber:2305306,
           studentName:"Husanpreet Singh",
            FatherName:"Jaswinder Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:10,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"P",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:18,
            rollNumber:2305307,
           studentName:"Indrajeet Singh Mukhiya",
            FatherName:"Vinod Mukhiya",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.50,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:19,
            rollNumber:2305308,
            studentName:"Isha Thappa",
            FatherName:"Bharat Bushan",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.20,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:20,
            rollNumber:2305309,
            studentName:"Jasleen Kaur",
            FatherName:"Harbans Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:0,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(Internal)/ Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(Internal)/ Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"Failed(Internal)/ Absent(External)",
                    status:"re-appear"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"Failed(Internal)/ Absent(External)",
                    status:"re-appear"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(Internal)/ Absent(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
            }
        },
        {
            s_no:21,
            rollNumber:23053010,
            studentName:"Jaspreet Kaur",
            FatherName:"Amarjeet Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(Internal)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:22,
            rollNumber:23053011,
            studentName:"Justin Wellington Chada",
            FatherName:"Max Chada",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.50,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
            }
        },
        {
            s_no:23,
            rollNumber:23053012,
            studentName:"Karan Kumar Paswan",
            FatherName:"Dina Nath Paswan",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(Int)/Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:24,
            rollNumber:23053013,
            studentName:"Kashish",
            FatherName:"Varinder Kumar",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:6.95,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:25,
            rollNumber:23053014,
            studentName:"Komalpreet Kaur",
            FatherName:"Kulbir Singh",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.65,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
            }
        },
        {
            s_no:26,
            rollNumber:23053015,
            studentName:"Lakshay Katoch",
            FatherName:"Sehdev Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:27,
            rollNumber:23053016,
            studentName:"Leishangthem Lojingngamba Khaba",
            FatherName:"Leishangthem Bobi Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:5,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"Failed(Internal)/Absent(External)",
                    status:"re-appear"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:28,
            rollNumber:23053019,
            studentName:"MD Sahid Alam",
            FatherName:"Shabnam Pravin",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.00,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:29,
            rollNumber:2305320,
            studentName:"Mohammad Anwar",
            FatherName:"MD Mustaque Ahmad",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:30,
            rollNumber:2305321,
            studentName:"Mohammad Umar Farooq",
            FatherName:"Mohammad Maqsood Alam",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.00,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:31,
            rollNumber:2305322,
            studentName:"Muskan Kumari",
            FatherName:"Aklesh Parsad",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.75,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:32,
            rollNumber:2305323,
            studentName:"Mwaalu Muloongo",
            FatherName:"Best Munyama Muloongo",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.10,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:33,
            rollNumber:2305325,
            studentName:"Prakriti Upadhyay",
            FatherName:"Abhimanyu Upadhayay",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.30,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:34,
            rollNumber:2305326,
            studentName:"Pritam Sinha",
            FatherName:"Golap Sinha",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.55,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
            }
        },
        {
            s_no:35,
            rollNumber:2305327,
            studentName:"Rakesh Kumar",
            FatherName:"Ram Hriday Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:36,
            rollNumber:2305328,
            studentName:"Ravneet Kaur",
            FatherName:"Gurpreet Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"P",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:37,
            rollNumber:2305329,
            studentName:"S Rehan Haider",
            FatherName:"MD Hasan",
            resultStatus:"re-appear",
            passed:false,
            credits:17,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:38,
            rollNumber:2305331,
            studentName:"Sajjad Ali",
            FatherName:"Syed Reyaz Al Rizvi",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.25,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:39,
            rollNumber:2305332,
            studentName:"Saurabh",
            FatherName:"Sanjeev Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:9,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:40,
            rollNumber:2305333,
            studentName:"Shekina Nokukhanya Ncube",
            FatherName:"Mkhanyiseli Ncube",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.75,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:41,
            rollNumber:2305334,
            studentName:"Shekina Nokukhanya Ncube",
            FatherName:"Mkhanyiseli Ncube",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:6.30,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"C",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:42,
            rollNumber:2305335,
            studentName:"Surbhi Suman",
            FatherName:"Saroj Kumar",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.60,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:43,
            rollNumber:2305336,
            studentName:"Thomas Isheanesu Kazonda",
            FatherName:"Thomas Kazonda",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:8.00,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"O",
                    status:"pass"
                },
            }
        },
        {
            s_no:44,
            rollNumber:2305337,
            studentName:"Vanshika",
            FatherName:"Sanjeev Kumar",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.35,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:45,
            rollNumber:2305338,
            studentName:"Vanshika",
            FatherName:"Charanjit Kumar",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.85,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                   gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:46,
            rollNumber:2305339,
            studentName:"Varinder Singh",
            FatherName:"Satnam Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:7,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"C",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:47,
            rollNumber:2305340,
            studentName:"Vipan Sharma",
            FatherName:"Ranjeep Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:16,
            SGPA:null,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:48,
            rollNumber:2305317,
            studentName:"MD Farhan Alam",
            FatherName:"Aftab Ahmad",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:6.80,
            gradeDetails:{
               Mentoring_And_Proffesional_Development:{
                    qualitative_meaning:0,
                    gradeSymbol:"S",
                    status:"pass",
                },
                Engineering_Mathematics_ii:{
                    qualitative_meaning:4,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Chemistry_1:{
                    qualitative_meaning:4,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Chemistry_1_lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English:{
                    qualitative_meaning:1,
                    gradeSymbol:"B",
                    status:"pass"
                },
                English_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                WorkShop:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                PPS:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                PPS_Lab:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
    ]
}


export default secondSemResults