const thirdSemResults = {
    release_date:"",
    results:[
        {
            s_no:1,
            rollNumber:2305289,
            studentName:"Aarush Pupneja",
            FatherName:"Azad Pupneja",
            resultStatus:"re-appear",
            passed:false,
            credits:12,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },

            }
        },
        {
            s_no:2,
            rollNumber:2305290,
            studentName:"Abdul Ahad",
            FatherName:"Mohammad Khalid",
            resultStatus:"re-appear",
            passed:false,
            credits:15,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
            }
        },
        {
            s_no:3,
            rollNumber:2305291,
           studentName:"Abhishek Kumar",
            FatherName:"Ashok Kumar Sinha",
            resultStatus:"re-appear",
            passed:false,
            credits:15,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },

            }
        },
        {
            s_no:4,
            rollNumber:2305292,
           studentName:"Abhishek Thakur",
            FatherName:"Raj Kumar ",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.33,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },

            }
        },
        {
            s_no:5,
            rollNumber:2305293,
           studentName:"Amanjot Kaur",
            FatherName:"Lakhvir Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.24,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },

            }
        },
        {
            s_no:6,
            rollNumber:2305294,
           studentName:"Anshu Sharma",
            FatherName:"Bhagwan Dass Sharma",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.43,
            gradeDetails:{
              Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:7,
            rollNumber:2305295,
           studentName:"Ashish Kallu",
            FatherName:"Gulu Ram",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.10,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },

            }
        },
        {
            s_no:8,
            rollNumber:2305296,
           studentName:"Ashvani Yadav",
            FatherName:"Narendra Yadav",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:6.57,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
            }
        },
        {
            s_no:9,
            rollNumber:2305297,
           studentName:"Ayush Kumar",
            FatherName:"Haresh Kumar",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:6.57,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },

            }
        },
        {
            s_no:10,
            rollNumber:2305298,
           studentName:"Bappa Suklabaidya",
            FatherName:"Bablu Suklabaidya",
            resultStatus:"re-appear",
            passed:false,
            credits:12,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(Internal)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"P",
                    status:"pass"
                },

            }
        },
        {
            s_no:11,
            rollNumber:2305299,
           studentName:"Birenda Kumar",
            FatherName:"Madhu Prasad",
            resultStatus:"re-appear",
            passed:false,
            credits:15,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(Internal)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"P",
                    status:"pass"
                },

            }
        },
        {
            s_no:12,
            rollNumber:2305300,
           studentName:"Bishal Kumar Sah",
            FatherName:"Maheshwar Sah",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.43,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"O",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
            }
        },
        {
            s_no:13,
            rollNumber:2305301,
           studentName:"Bizumremyi Gervais",
            FatherName:"Patrick Mugenga",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.10,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:14,
            rollNumber:2305302,
           studentName:"Desire Musarafu",
            FatherName:"Sheppard Musarafu",
            resultStatus:"pass",
            passed:true,
            credits:18,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },

            }
        },
        {
            s_no:15,
            rollNumber:2305303,
           studentName:"Faisal Ashraf Dar",
            FatherName:"Mohammad Ashraf Dar",
            resultStatus:"re-appear",
            passed:false,
            credits:15,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },

            }
        },
        {
            s_no:16,
            rollNumber:2305304,
           studentName:"Hanzala Safi",
            FatherName:"Safi Alam",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.57,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        // {
        //     s_no:17,
        //     rollNumber:2305306,
        //    studentName:"Husanpreet Singh",
        //     FatherName:"Jaswinder Singh",
        //     resultStatus:"re-appear",
        //     passed:false,
        //     credits:10,
        //     SGPA:null,
        //     gradeDetails:{
        //        Mentoring_And_Proffesional_Development:{
        //             qualitative_meaning:0,
        //             gradeSymbol:"S",
        //             status:"pass",
        //         },
        //         Engineering_Mathematics_ii:{
        //             qualitative_meaning:4,
        //             gradeSymbol:"Failed(External)",
        //             status:"re-appear"
        //         },
        //         Chemistry_1:{
        //             qualitative_meaning:4,
        //             gradeSymbol:"C",
        //             status:"pass"
        //         },
        //         Chemistry_1_lab:{
        //             qualitative_meaning:1,
        //             gradeSymbol:"C",
        //             status:"pass"
        //         },
        //         English:{
        //             qualitative_meaning:1,
        //             gradeSymbol:"P",
        //             status:"pass"
        //         },
        //         English_Lab:{
        //             qualitative_meaning:2,
        //             gradeSymbol:"B+",
        //             status:"pass"
        //         },
        //         WorkShop:{
        //             qualitative_meaning:3,
        //             gradeSymbol:"Absent(External)",
        //             status:"re-appear"
        //         },
        //         PPS:{
        //             qualitative_meaning:3,
        //             gradeSymbol:"Failed(External)",
        //             status:"re-appear"
        //         },
        //         PPS_Lab:{
        //             qualitative_meaning:3,
        //             gradeSymbol:"A",
        //             status:"pass"
        //         },
        //     }
        // },
        {
            s_no:18,
            rollNumber:2305307,
           studentName:"Indrajeet Singh Mukhiya",
            FatherName:"Vinod Mukhiya",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.24,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:19,
            rollNumber:2305308,
            studentName:"Isha Thappa",
            FatherName:"Bharat Bushan",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.38,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:20,
            rollNumber:2305309,
            studentName:"Jasleen Kaur",
            FatherName:"Harbans Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:6.86,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:21,
            rollNumber:23053010,
            studentName:"Jaspreet Kaur",
            FatherName:"Amarjeet Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.67,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        // {
        //     s_no:22,
        //     rollNumber:23053011,
        //     studentName:"Justin Wellington Chada",
        //     FatherName:"Max Chada",
        //     resultStatus:"pass",
        //     passed:true,
        //     credits:20,
        //     SGPA:8.50,
        //     gradeDetails:{
        //        Mentoring_And_Proffesional_Development:{
        //             qualitative_meaning:0,
        //             gradeSymbol:"S",
        //             status:"pass",
        //         },
        //         Engineering_Mathematics_ii:{
        //             qualitative_meaning:4,
        //             gradeSymbol:"B+",
        //             status:"pass"
        //         },
        //         Chemistry_1:{
        //             qualitative_meaning:4,
        //             gradeSymbol:"A",
        //             status:"pass"
        //         },
        //         Chemistry_1_lab:{
        //             qualitative_meaning:1,
        //             gradeSymbol:"O",
        //             status:"pass"
        //         },
        //         English:{
        //             qualitative_meaning:1,
        //             gradeSymbol:"A",
        //             status:"pass"
        //         },
        //         English_Lab:{
        //             qualitative_meaning:2,
        //             gradeSymbol:"O",
        //             status:"pass"
        //         },
        //         WorkShop:{
        //             qualitative_meaning:3,
        //             gradeSymbol:"O",
        //             status:"pass"
        //         },
        //         PPS:{
        //             qualitative_meaning:3,
        //             gradeSymbol:"A",
        //             status:"pass"
        //         },
        //         PPS_Lab:{
        //             qualitative_meaning:3,
        //             gradeSymbol:"O",
        //             status:"pass"
        //         },
        //     }
        // },
        {
            s_no:23,
            rollNumber:23053012,
            studentName:"Karan Kumar Paswan",
            FatherName:"Dina Nath Paswan",
            resultStatus:"re-appear",
            passed:false,
            credits:18,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"P",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:24,
            rollNumber:23053013,
            studentName:"Kashish",
            FatherName:"Varinder Kumar",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:6.95,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
            }
        },
        {
            s_no:25,
            rollNumber:23053014,
            studentName:"Komalpreet Kaur",
            FatherName:"Kulbir Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.29,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:26,
            rollNumber:23053015,
            studentName:"Lakshay Katoch",
            FatherName:"Sehdev Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.00,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"C",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:27,
            rollNumber:23053016,
            studentName:"Leishangthem Lojingngamba Khaba",
            FatherName:"Leishangthem Bobi Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:6,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
            }
        },
        {
            s_no:28,
            rollNumber:23053019,
            studentName:"MD Sahid Alam",
            FatherName:"Shabnam Pravin",
            resultStatus:"re-appear",
            passed:false,
            credits:18,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:29,
            rollNumber:2305320,
            studentName:"Mohammad Anwar",
            FatherName:"MD Mustaque Ahmad",
            resultStatus:"re-appear",
            passed:false,
            credits:18,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"P",
                    status:"pass"
                },
            }
        },
        {
            s_no:30,
            rollNumber:2305321,
            studentName:"Mohammad Umar Farooq",
            FatherName:"Mohammad Maqsood Alam",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.33,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:31,
            rollNumber:2305322,
            studentName:"Muskan Kumari",
            FatherName:"Aklesh Parsad",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.52,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:32,
            rollNumber:2305323,
            studentName:"Mwaalu Muloongo",
            FatherName:"Best Munyama Muloongo",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.52,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:33,
            rollNumber:2305325,
            studentName:"Prakriti Upadhyay",
            FatherName:"Abhimanyu Upadhayay",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.29,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:34,
            rollNumber:2305326,
            studentName:"Pritam Sinha",
            FatherName:"Golap Sinha",
            resultStatus:"pass",
            passed:true,
            credits:20,
            SGPA:7.95,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"O",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:35,
            rollNumber:2305327,
            studentName:"Rakesh Kumar",
            FatherName:"Ram Hriday Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:15,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(Internal)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:36,
            rollNumber:2305328,
            studentName:"Ravneet Kaur",
            FatherName:"Gurpreet Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:6.95,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:37,
            rollNumber:2305329,
            studentName:"S Rehan Haider",
            FatherName:"MD Hasan",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:6.81,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:38,
            rollNumber:2305331,
            studentName:"Sajjad Ali",
            FatherName:"Syed Reyaz Al Rizvi",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.19,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:39,
            rollNumber:2305332,
            studentName:"Saurabh",
            FatherName:"Sanjeev Kumar",
            resultStatus:"re-appear",
            passed:false,
            credits:18,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:40,
            rollNumber:2305333,
            studentName:"Shekina Nokukhanya Ncube",
            FatherName:"Mkhanyiseli Ncube",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.67,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:41,
            rollNumber:2305334,
            studentName:"Simran Kaur",
            FatherName:"Kajinder Singh",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.24,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:42,
            rollNumber:2305335,
            studentName:"Surbhi Suman",
            FatherName:"Saroj Kumar",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.48,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
        {
            s_no:43,
            rollNumber:2305336,
            studentName:"Thomas Isheanesu Kazonda",
            FatherName:"Thomas Kazonda",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.24,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:44,
            rollNumber:2305337,
            studentName:"Vanshika",
            FatherName:"Sanjeev Kumar",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.14,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:45,
            rollNumber:2305338,
            studentName:"Vanshika",
            FatherName:"Charanjit Kumar",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.43,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B",
                    status:"pass"
                },
            }
        },
        {
            s_no:46,
            rollNumber:2305339,
            studentName:"Varinder Singh",
            FatherName:"Satnam Singh",
            resultStatus:"re-appear",
            passed:false,
            credits:2,
            SGPA:null,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(Internal)",
                    status:"re-appear"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"Absent(Internal)",
                    status:"re-appear"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"Absent(Internal)",
                    status:"re-appear"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"Failed(External)",
                    status:"re-appear"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"Absent(External)",
                    status:"re-appear"
                },
            }
        },
        {
            s_no:47,
            rollNumber:2305340,
            studentName:"Vipan Sharma",
            FatherName:"Ranjeep Kumar",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:8.29,
            gradeDetails:{
              Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"A",
                    status:"pass"
                },
            }
        },
        {
            s_no:48,
            rollNumber:2305317,
            studentName:"MD Farhan Alam",
            FatherName:"Aftab Ahmad",
            resultStatus:"pass",
            passed:true,
            credits:21,
            SGPA:7.43,
            gradeDetails:{
               Mathematics_3:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass",
                },
                    DSA:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                OOP:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                DSA_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                OOP_Lab:{
                    qualitative_meaning:2,
                    gradeSymbol:"A",
                    status:"pass"
                },
                IT_Workshop:{
                    qualitative_meaning:1,
                    gradeSymbol:"A",
                    status:"pass"
                },
                Digital_Electronics:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
                Digital_Electronics_Lab:{
                    qualitative_meaning:1,
                    gradeSymbol:"A+",
                    status:"pass"
                },
                UHV_1:{
                    qualitative_meaning:3,
                    gradeSymbol:"B+",
                    status:"pass"
                },
            }
        },
    ]
}



export default thirdSemResults